### ISSUE TITLE
Feature request: ability to get page props

### ISSUE THREAD

**Issue by albertpratomo** [claudiodekker/inertia-laravel-testing#35]
Hi, previously in version 1, we were able to do `$response->inertiaProps()` which will return an array of props for the page.

This is really useful because we can snapshot the props and ensure that all props are there and correct.

In version 2, I'm missing this feature. Is there a way to get the props? I don't want to use `has` because my test file will be to complex.

Thanks before.

**Comment by claudiodekker** [comment]
Hi,

There isn't really a way to get the page props anymore directly, as the 'interaction check' already takes care of ensuring that you're testing against all props and that you aren't missing any. 

You're absolutely right that this check is only done inside `has` scopes and not on the root level, because some people have keys shared globally (e.g. `errors` or `auth`) that they don't _always_ want to assert exist everywhere. 

**However**, we still wanted to support this and added an option to our [configuration file](https://github.com/claudiodekker/inertia-laravel-testing#publishing-the-configuration-file) that allows you to [re-enable the automatic top/root-level interaction check](https://github.com/claudiodekker/inertia-laravel-testing/blob/master/config/inertia.php#L18) if you _do_ want this. If you _don't_ want this behaviour everywhere/globally, but only want it for the current assertion call, you may use the `interacted` method (which, admittedly, isn't documented, but is 100% usable / used under the hood):
```php
$response->assertInertia(fn (Assert $page) => $page
    ->has('subject')
    ->interacted()
);
```

Hope this helps, but feel free to re-open/comment on this issue if I'm mis-understanding your request!

**Comment by albertpratomo** [comment]
Hi @claudiodekker, thanks for the explanation. I would still like to propose that developer should have access to the page props.

My main reason is because I want to be able to "snapshot" the props. By using [this package](https://github.com/spatie/phpunit-snapshot-assertions), I was able to do:
```
$this->assertMatchesSnapshot($response->inertiaProps());
```

The code above will take a snapshot of the props and save it to a file. Then it will serve as the "source of truth" that future props will be compared against.

This will result in a less verbose tests because instead of having to call `has()` for each important props, I can just snapshot the whole props tree and see that it matches the previous snapshot ("source of truth"). For my app this was and is a very important assertion and the current version 2 is not yet supporting it..

**Comment by claudiodekker** [comment]
Ah, gotcha. Yeah, okay, that's a realistic use-case. Thanks!

Would it perhaps make sense to expose the `inertiaPage()` object instead? I can imagine that others who have similar requirements like yours might need the component too, as well as that it's more in-line with the recent transition from `$inertia.props` to `$inertia.page.props`. Of course, it wouldn't do things such as the automatic component existence check or whatever might be introduced in the future, but at least it's something.

What do you think, @reinink?

**Comment by albertpratomo** [comment]
Thanks! Yeah I think `inertiaPage()` is fine as well, as long as we could access the props. 😄

**Comment by claudiodekker** [comment]
Great! This'll be coming later today as part of the merger into https://github.com/inertiajs/inertia-laravel 👍
