### ISSUE TITLE
Add two_factor_enable to user test?

### ISSUE THREAD

**Issue by sunscreem** [claudiodekker/inertia-laravel-testing#7]
I'm rapidly falling in love with this package.

Just working through the examples in the readme and this one where you assert againsts a model:

```php
    /** @test */
    public function a_random_test(){

        $user = UserFactory::new()->create(['name' => 'John Doe']);

        $response = $this->actingAs($user)->get(route('dashboard'));

        $response->assertInertiaHas('user',$user);
       
    }
```

...fails (with a clean laravel/jetstream install - not using teams)

Maybe Laravel added the `two_factor_enable` recently or I need to tweak my user model?

```
1) Tests\Feature\OrganisationsTest::a_random_test
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
     'created_at' => '2020-10-17T18:07:55.000000Z'
     'id' => 1
     'profile_photo_url' => 'https://ui-avatars.com/api/?n...EBF4FF'
+    'two_factor_enabled' => false
 )
```

**Comment by claudiodekker** [comment]
Hi,

Yes, this is because Jetstream shares the user to Inertia globally, and adds the `two_factor_enabled` key: https://github.com/laravel/jetstream/blob/700c6350f0ce1b366f8bfb6e075a72584dd87a93/src/Http/Middleware/ShareInertiaData.php#L47-L49

My recommendation would be to basically what Jetstream does there.

Hope this helps!

**Comment by sunscreem** [comment]
Perfect! As you can still trying to wrap about whats inertia.js and what's Jetstream!
